//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMaps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marker
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public double longitude { get; set; }
        public double latitude { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string type { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
